const gbe = @import("gbe");
const C = @import("components.zig");

pub const GameSession = gbe.Session(struct {
    Animation: gbe.ComponentList(C.Animation, 10),
    Bullet: gbe.ComponentList(C.Bullet, 10),
    Creature: gbe.ComponentList(C.Creature, 100),
    GameController: gbe.ComponentList(C.GameController, 1),
    MainController: gbe.ComponentList(C.MainController, 1),
    Monster: gbe.ComponentList(C.Monster, 50),
    PhysObject: gbe.ComponentList(C.PhysObject, 100),
    Pickup: gbe.ComponentList(C.Pickup, 10),
    Player: gbe.ComponentList(C.Player, 50),
    PlayerController: gbe.ComponentList(C.PlayerController, 4),
    RemoveTimer: gbe.ComponentList(C.RemoveTimer, 50),
    SimpleGraphic: gbe.ComponentList(C.SimpleGraphic, 50),
    Transform: gbe.ComponentList(C.Transform, 100),
    Voice: gbe.ComponentList(C.Voice, 100),
    Web: gbe.ComponentList(C.Web, 100),
    EventAwardLife: gbe.ComponentList(C.EventAwardLife, 20),
    EventAwardPoints: gbe.ComponentList(C.EventAwardPoints, 20),
    EventCollide: gbe.ComponentList(C.EventCollide, 50),
    EventConferBonus: gbe.ComponentList(C.EventConferBonus, 5),
    EventDraw: gbe.ComponentList(C.EventDraw, 100),
    EventDrawBox: gbe.ComponentList(C.EventDrawBox, 100),
    EventInput: gbe.ComponentList(C.EventInput, 20),
    EventMonsterDied: gbe.ComponentList(C.EventMonsterDied, 20),
    EventPlayerDied: gbe.ComponentList(C.EventPlayerDied, 20),
    EventPlayerOutOfLives: gbe.ComponentList(C.EventPlayerOutOfLives, 20),
    EventPostScore: gbe.ComponentList(C.EventPostScore, 20),
    EventQuit: gbe.ComponentList(C.EventQuit, 5),
    EventSaveHighScore: gbe.ComponentList(C.EventSaveHighScore, 5),
    EventShowMessage: gbe.ComponentList(C.EventShowMessage, 5),
    EventTakeDamage: gbe.ComponentList(C.EventTakeDamage, 20),
});
